[package]
name = "login_stub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#remote
crossbeam = "0.8"

#local
daemon_lib = { path="../../daemon_lib" }
